#!/bin/bash
#### "***********************************************"
#### "*       ..:: Script por Tochtly ::..           *"
#### "*  Soporte: https://github.com/itorres2020     *"
#### "*       E-Mail: contacto@tochtly.com           *"
#### "***********************************************"

#### Ejecutar el script de instalación ####
if [ -f /tmp/DzOSat/installOSCam.sh ]; then
    sh /tmp/DzOSat/installOSCam.sh
    sleep 3
else
    echo "¡Script no encontrado!"
    exit 0
fi

#### Eliminar carpeta temporal de OSCam ####
rm -r /tmp/DzOSat >/dev/null 2>&1

echo ""
echo ""
echo "-------------------------------------------------------"
echo "* Archivos de configuración y Softcam en [/etc/tuxbox/config] *"
echo "-------------------------------------------------------"
echo ""
echo ""
echo "*******************************************"
echo "*             Instalación finalizada      *"
echo "*                                         *"
echo "*         Es necesario reiniciar Enigma2  *"
echo "*                                         *"
echo "*    Parcheado y compilado por Tochtly    *"
echo "*                                         *"
echo "*******************************************"

#### Eliminar archivo IPK ####
for file in /tmp/enigma2-plugin-softcams-oscam*.ipk; do
    if [ -f "$file" ]; then
        rm -rf /tmp/enigma2-plugin-softcams-oscam*.ipk
        sleep 3
    fi
done

#### Reiniciar la imagen ####
killall -9 enigma2

exit 0
