#!/bin/bash
#### "***********************************************"
#### "*       ..:: Script by MOHAMED_OS ::..        *"
#### "*  Support: https://github.com/MOHAMED19OS    *"
#### "*       E-Mail: mohamed19eng@gmail.com        *"
#### "***********************************************"
FIN="=================================================="

#### Path ####
usrlibpath="/usr/lib"
libpath="/lib"

#### checking Package: libssl & libcrypto ####
if [ -f /etc/apt/apt.conf ]; then
    images="OE2.5 IMAGES:"
    STATUS="/var/lib/dpkg/status"
    OPKG='apt-get update'
    OPKGINSTAL='apt-get install'
    OPKGREMOV='apt-get purge --auto-remove'
elif [ -f /etc/opkg/opkg.conf ]; then
    images="OE2.0 IMAGES:"
    STATUS='/var/lib/opkg/status'
    OPKG='opkg update'
    OPKGINSTAL='opkg install'
    OPKGREMOV='opkg remove --force-depends'
else
    echo "Sorry, your device not have the opkg/dpkg folder :("
fi

if [ -d "/etc/tuxbox/config" ]; then
    mv /etc/tuxbox/config /etc/tuxbox/config_backup >/dev/null 2>&1
fi

${OPKGREMOV} enigma2-plugin-softcams-oscam >/dev/null 2>&1

if [ -d "/etc/tuxbox/config_backup" ]; then
    mv /etc/tuxbox/config_backup /etc/tuxbox/config >/dev/null 2>&1
fi

sleep 3
${OPKG} >/dev/null 2>&1

#### libssl ####
if grep -qs 'Package: libssl3' ${STATUS}; then
    echo "${images} libssl3"
    ln -s libssl.so.3 ${usrlibpath}/libssl.so.1.1 >/dev/null 2>&1
    ln -s libssl.so.3 ${usrlibpath}/libssl.so.1.0.0 >/dev/null 2>&1
    ln -s ${usrlibpath}/libssl.so.3 ${libpath}/libssl.so.1.1 >/dev/null 2>&1
    ln -s ${usrlibpath}/libssl.so.3 ${libpath}/libssl.so.1.0.0 >/dev/null 2>&1
elif grep -qs 'Package: libssl1.1' ${STATUS}; then
    echo "$images libssl1.1"
    ln -s libssl.so.1.1 ${usrlibpath}/libssl.so.1.0.0 >/dev/null 2>&1
    ln -s ${usrlibpath}/libssl.so.1.1 ${libpath}/libssl.so.1.0.0 >/dev/null 2>&1
elif grep -qs 'Package: libssl1.0.2' ${STATUS}; then
    echo "$images libssl.1.0.2"
    ln -s libssl.so.1.0.2 ${usrlibpath}/libssl.so.1.0.0 >/dev/null 2>&1
    ln -s ${usrlibpath}/libssl.so.1.0.2 ${libpath}/libssl.so.1.0.0 >/dev/null 2>&1
elif [ -f /usr/lib/libssl.so.3 ]; then
    echo "$images libssl3"
    ln -s libssl.so.3 ${usrlibpath}/libssl.so.1.1 >/dev/null 2>&1
    ln -s libssl.so.3 ${usrlibpath}/libssl.so.1.0.0 >/dev/null 2>&1
    ln -s ${usrlibpath}/libssl.so.3 ${libpath}/libssl.so.1.1 >/dev/null 2>&1
    ln -s ${usrlibpath}/libssl.so.3 ${libpath}/libssl.so.1.0.0 >/dev/null 2>&1
elif [ -f /usr/lib/libssl.so.1.1 ]; then
    echo "$images libssl1.1"
    ln -s libssl.so.1.1 ${usrlibpath}/libssl.so.1.0.0 >/dev/null 2>&1
    ln -s ${usrlibpath}/libssl.so.1.1 ${libpath}/libssl.so.1.0.0 >/dev/null 2>&1
elif [ -f /usr/lib/libssl.so.1.0.2 ]; then
    echo "$images libssl.1.0.2"
    ln -s libssl.so.1.0.2 ${usrlibpath}/libssl.so.1.0.0 >/dev/null 2>&1
    ln -s ${usrlibpath}/libssl.so.1.0.2 ${libpath}/libssl.so.1.0.0 >/dev/null 2>&1
else ## Try to Download libssl from feed
    if ! grep -qs 'Package: libssl3' ${STATUS}; then
        echo "install libssl3"
        ${OPKGINSTAL} libssl3 >/dev/null 2>&1
        ln -s libssl.so.3 ${usrlibpath}/libssl.so.1.1 >/dev/null 2>&1
        ln -s libssl.so.3 ${usrlibpath}/libssl.so.1.0.0 >/dev/null 2>&1
        ln -s ${usrlibpath}/libssl.so.3 ${libpath}/libssl.so.1.1 >/dev/null 2>&1
        ln -s ${usrlibpath}/libssl.so.3 ${libpath}/libssl.so.1.0.0 >/dev/null 2>&1
    elif ! grep -qs 'Package: libssl1.1' ${STATUS}; then
        echo "install libssl1.1"
        ${OPKGINSTAL} libssl1.1 >/dev/null 2>&1
        ln -s libssl.so.1.1 ${usrlibpath}/libssl.so.1.0.0 >/dev/null 2>&1
        ln -s ${usrlibpath}/libssl.so.1.1 ${libpath}/libssl.so.1.0.0 >/dev/null 2>&1
    elif ! grep -qs 'Package: libssl1.0.2' ${STATUS}; then
        echo "install libssl1.0.2"
        ${OPKGINSTAL} libssl1.0.2 >/dev/null 2>&1
        ln -s libssl.so.1.0.2 ${usrlibpath}/libssl.so.1.0.0 >/dev/null 2>&1
        ln -s ${usrlibpath}/libssl.so.1.0.2 ${libpath}/libssl.so.1.0.0 >/dev/null 2>&1
    else
        echo ${FIN}
        echo "ERROR: The libsslx.x.x file could not be loaded from the repository."
        echo ${FIN}
        exit 1
    fi
fi

#### libcrypto ####
if grep -qs 'Package: libcrypto3' ${STATUS}; then
    echo "$images libcrypto3"
    ln -s libcrypto.so.3 ${usrlibpath}/libcrypto.so.1.1 >/dev/null 2>&1
    ln -s libcrypto.so.3 ${usrlibpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
    ln -s ${usrlibpath}/libcrypto.so.3 ${libpath}/libcrypto.so.1.1 >/dev/null 2>&1
    ln -s ${usrlibpath}/libcrypto.so.3 ${libpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
elif grep -qs 'Package: libcrypto1.1' ${STATUS}; then
    echo "$images libcrypto1.1"
    ln -s libcrypto.so.1.1 ${usrlibpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
    ln -s ${usrlibpath}/libcrypto.so.1.1 ${libpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
elif grep -qs 'Package: libcrypto1.0.2' ${STATUS}; then
    echo "$images libcrypto.1.0.2"
    ln -s libcrypto.so.1.0.2 ${usrlibpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
    ln -s ${usrlibpath}/libcrypto.so.1.0.2 ${libpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
elif [ -f /usr/lib/libcrypto.so.3 ]; then
    echo "$images libcrypto3"
    ln -s libcrypto.so.3 ${usrlibpath}/libcrypto.so.1.1 >/dev/null 2>&1
    ln -s libcrypto.so.3 ${usrlibpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
    ln -s ${usrlibpath}/libcrypto.so.3 ${libpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
elif [ -f /usr/lib/libcrypto.so.1.1 ]; then
    echo "$images libcrypto1.1"
    ln -s libcrypto.so.1.1 ${usrlibpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
    ln -s ${usrlibpath}/libcrypto.so.1.1 ${libpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
elif [ -f /usr/lib/libcrypto.so.1.0.2 ]; then
    echo "$images libcrypto.1.0.2"
    ln -s libcrypto.so.1.0.2 ${usrlibpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
    ln -s ${usrlibpath}/libcrypto.so.1.0.2 ${libpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
else ## Try to Download libcrypto from feed
    if ! grep -qs 'Package: libcrypto3' ${STATUS}; then
        echo "install libcrypto3"
        ${OPKGINSTAL} libcrypto3 >/dev/null 2>&1
        ln -s libcrypto.so.3 ${usrlibpath}/libcrypto.so.1.1 >/dev/null 2>&1
        ln -s libcrypto.so.3 ${usrlibpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
        ln -s ${usrlibpath}/libcrypto.so.3 ${libpath}/libcrypto.so.1.1 >/dev/null 2>&1
        ln -s ${usrlibpath}/libcrypto.so.3 ${libpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
    elif ! grep -qs 'Package: libcrypto1.1' ${STATUS}; then
        echo "install libcrypto1.1"
        ${OPKGINSTAL} libcrypto1.1 >/dev/null 2>&1
        ln -s libcrypto.so.1.1 ${usrlibpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
        ln -s ${usrlibpath}/libcrypto.so.1.1 ${libpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
    elif ! grep -qs 'Package: libcrypto1.0.2' ${STATUS}; then
        echo "install libcrypto1.0.2"
        ${OPKGINSTAL} libcrypto1.0.2 >/dev/null 2>&1
        ln -s libcrypto.so.1.0.2 ${usrlibpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
        ln -s ${usrlibpath}/libcrypto.so.1.0.2 ${libpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
    else
        echo ${FIN}
        echo "ERROR: The libcryptox.x.x file could not be loaded from the repository."
        echo ${FIN}
        exit 1
    fi
fi

exit 0
