#!/bin/bash
#### "***********************************************"
#### "*       ..:: Script por Tochtly ::..           *"
#### "*  Soporte: https://github.com/itorres2020     *"
#### "*       E-Mail: contacto@tochtly.com           *"
#### "***********************************************"
FIN="=================================================="

#### Rutas ####
usrlibpath="/usr/lib"
libpath="/lib"

#### Verificando Paquetes: libssl y libcrypto ####
if [ -f /etc/apt/apt.conf ]; then
    images="IMÁGENES OE2.5:"
    STATUS="/var/lib/dpkg/status"
    OPKG='apt-get update'
    OPKGINSTAL='apt-get install'
    OPKGREMOV='apt-get purge --auto-remove'
elif [ -f /etc/opkg/opkg.conf ]; then
    images="IMÁGENES OE2.0:"
    STATUS='/var/lib/opkg/status'
    OPKG='opkg update'
    OPKGINSTAL='opkg install'
    OPKGREMOV='opkg remove --force-depends'
else
    echo "Lo sentimos, tu dispositivo no tiene la carpeta opkg/dpkg :("
fi

if [ -d "/etc/tuxbox/config" ]; then
    mv /etc/tuxbox/config /etc/tuxbox/config_backup >/dev/null 2>&1
fi

${OPKGREMOV} enigma2-plugin-softcams-oscam >/dev/null 2>&1

if [ -d "/etc/tuxbox/config_backup" ]; then
    mv /etc/tuxbox/config_backup /etc/tuxbox/config >/dev/null 2>&1
fi

sleep 3
${OPKG} >/dev/null 2>&1

#### Configuración de libssl ####
if grep -qs 'Package: libssl3' ${STATUS}; then
    echo "${images} libssl3"
    ln -s libssl.so.3 ${usrlibpath}/libssl.so.1.1 >/dev/null 2>&1
    ln -s libssl.so.3 ${usrlibpath}/libssl.so.1.0.0 >/dev/null 2>&1
    ln -s ${usrlibpath}/libssl.so.3 ${libpath}/libssl.so.1.1 >/dev/null 2>&1
    ln -s ${usrlibpath}/libssl.so.3 ${libpath}/libssl.so.1.0.0 >/dev/null 2>&1
elif grep -qs 'Package: libssl1.1' ${STATUS}; then
    echo "$images libssl1.1"
    ln -s libssl.so.1.1 ${usrlibpath}/libssl.so.1.0.0 >/dev/null 2>&1
    ln -s ${usrlibpath}/libssl.so.1.1 ${libpath}/libssl.so.1.0.0 >/dev/null 2>&1
elif grep -qs 'Package: libssl1.0.2' ${STATUS}; then
    echo "$images libssl.1.0.2"
    ln -s libssl.so.1.0.2 ${usrlibpath}/libssl.so.1.0.0 >/dev/null 2>&1
    ln -s ${usrlibpath}/libssl.so.1.0.2 ${libpath}/libssl.so.1.0.0 >/dev/null 2>&1
else
    echo ${FIN}
    echo "ERROR: No se pudo cargar el archivo libssl desde el repositorio."
    echo ${FIN}
    exit 1
fi

#### Configuración de libcrypto ####
if grep -qs 'Package: libcrypto3' ${STATUS}; then
    echo "$images libcrypto3"
    ln -s libcrypto.so.3 ${usrlibpath}/libcrypto.so.1.1 >/dev/null 2>&1
    ln -s libcrypto.so.3 ${usrlibpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
    ln -s ${usrlibpath}/libcrypto.so.3 ${libpath}/libcrypto.so.1.1 >/dev/null 2>&1
    ln -s ${usrlibpath}/libcrypto.so.3 ${libpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
elif grep -qs 'Package: libcrypto1.1' ${STATUS}; then
    echo "$images libcrypto1.1"
    ln -s libcrypto.so.1.1 ${usrlibpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
    ln -s ${usrlibpath}/libcrypto.so.1.1 ${libpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
elif grep -qs 'Package: libcrypto1.0.2' ${STATUS}; then
    echo "$images libcrypto.1.0.2"
    ln -s libcrypto.so.1.0.2 ${usrlibpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
    ln -s ${usrlibpath}/libcrypto.so.1.0.2 ${libpath}/libcrypto.so.1.0.0 >/dev/null 2>&1
else
    echo ${FIN}
    echo "ERROR: No se pudo cargar el archivo libcrypto desde el repositorio."
    echo ${FIN}
    exit 1
fi

exit 0
